include $(SEISFS_HOME)/Makefile.global


#targets
VERSION = 0.1
TARGETANAME = libseisfile.a
TARGETADIRForCore = $(SEISFILE_HOME)/lib
TARGETA = $(TARGETADIRForCore)/$(TARGETANAME)
TARGETDNAME = libseisfile.so
TARGETDPATH = $(SEISFILE_HOME)/lib


LIBS += -L$(SEISFS_HOME)/lib -lseisfs
LIBS += -L$(SEISFILENAS_HOME)/lib -lsfnas
LIBS += -L$(SEISFILEHDFS_HOME)/lib -lsfhdfs
#LIBS += -L$(GCACHE_HOME)/lib -lsfgcache
LIBS += -L$(GPP)/lib -lgpp -lgpptbb -lgpptbbmalloc
