include $(SEISFS_HOME)/Makefile.global


#targets
VERSION = 0.1
TARGETANAME = libsfnas.a
TARGETADIRForCore = $(SEISFILENAS_HOME)/lib
TARGETA = $(TARGETADIRForCore)/$(TARGETANAME)
TARGETDNAME = libsfnas.so
TARGETDPATH = $(SEISFILENAS_HOME)/lib

LIBS	+= -L$(GEFILE_HOME)/lib -ldpi_fs_cssl
LIBS	+= -lxml2

