
include $(SEISFS_HOME)/Makefile.global


#targets
VERSION = 0.1
TARGETANAME = libseisfs.a
TARGETADIRForCore = $(SEISFS_HOME)/lib
TARGETA = $(TARGETADIRForCore)/$(TARGETANAME)
TARGETDNAME = libseisfs.so
TARGETDPATH = $(SEISFS_HOME)/lib

