include $(SEISFS_HOME)/Makefile.global


#targets
VERSION = 0.1
TARGETANAME = libseiscache.a
TARGETADIRForCore = $(SEISCACHE_HOME)/lib
TARGETA = $(TARGETADIRForCore)/$(TARGETANAME)
TARGETDNAME = libseiscache.so
TARGETDPATH = $(SEISCACHE_HOME)/lib


LIBS    += -L$(SEISFILE_HOME)/lib -lseisfile
LIBS    += -L$(GLOCK_HOME) -lglock
LIBS    += -L$(ZOOKEEPER_INSTALL)/lib -lzookeeper_mt
