include $(SEISFS_HOME)/Makefile.global


#targets
VERSION = 0.1
TARGETANAME = libsfgcache.a
TARGETADIRForCore = $(GCACHE_HOME)/lib
TARGETA = $(TARGETADIRForCore)/$(TARGETANAME)
TARGETDNAME = libsfgcache.so
TARGETDPATH = $(GCACHE_HOME)/lib

LIBS +=  -L$(HDFS_LIB) -lhdfs3
LIBS +=  -L$(ZSTD_HOME)/lib -lzstd


